### ISSUE TITLE
Does not support analyzer v4

### ISSUE THREAD

**Issue by maxlapides** [kiwi-bop/intl_generator#13]
```
flutter pub run intl_generator:extract_to_arb --output-dir=lib/l10n/gen lib/l10n/l10n.dart --warnings-are-errors --suppress-last-modified
Failed to build intl_generator:extract_to_arb:
/home/runner/.pub-cache/hosted/pub.dartlang.org/intl_generator-0.2.1/lib/extract_messages.dart:26:8: Error: Error when reading '/home/runner/.pub-cache/hosted/pub.dartlang.org/analyzer-4.0.0/lib/dart/ast/standard_ast_factory.dart': No such file or directory
import 'package:analyzer/dart/ast/standard_ast_factory.dart';
       ^
/home/runner/.pub-cache/hosted/pub.dartlang.org/intl_generator-0.2.1/lib/extract_messages.dart:173:7: Error: Undefined name 'astFactory'.
      astFactory.formalParameterList(Token.eof(0), [], null, null, Token.eof(0));
      ^^^^^^^^^^
pub finished with exit code 1
```

**Comment by mono0926** [comment]
You can use https://github.com/mono0926/intl_translation/tree/analyzer4 temporarily.

```yaml
  intl_generator:
    git:
      url: https://github.com/mono0926/intl_translation
      ref: analyzer4
```
